### ISSUE TITLE
Can you explain usage a little more?

### ISSUE THREAD

**Issue by Nantris** [jimmywarting/Screw-FileReader#1]
Is this actually something meant to be used with a require statement?

I'm not understanding implementation, but this seems very useful.

I see this answer on Stack, but I don't understand how this is example is using Screw-FileReader either: https://stackoverflow.com/questions/39849193/how-to-detect-filereader-load-end

Thanks for contributing to the community!

**Comment by jimmywarting** [comment]
This lib will add new methods to Blobs prototype so you can call eg ‘blob.arrayBuffer().then(successFn)‘ and all the other methods described in the readme. It supports es6 import, commonJs, or you can just include the index.js file anywhere. And that's it

You don't have to to much Since it add the methods to the blob prototype and it doesn't have any exports
